"""crear_tablas_inventario

Revision ID: f637358567b0
Revises: 
Create Date: 2026-06-10 23:15:54.736719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f637358567b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('dataset_entrenamiento',
    sa.Column('id_dataset', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_dataset', sa.String(length=150), nullable=False),
    sa.Column('fecha_generacion', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('registros', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_dataset')
    )
    op.create_table('proveedores',
    sa.Column('id_proveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.Column('ruc', sa.String(length=13), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor'),
    sa.UniqueConstraint('ruc')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('modelos_ia',
    sa.Column('id_modelo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_dataset', sa.Integer(), nullable=False),
    sa.Column('algoritmo', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('mae', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rmse', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('mape', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fecha_entrenamiento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_dataset'], ['dataset_entrenamiento.id_dataset'], ),
    sa.PrimaryKeyConstraint('id_modelo')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_codigo'), ['codigo'], unique=True)

    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_correo'), ['correo'], unique=True)

    op.create_table('alertas',
    sa.Column('id_alerta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('tipo_alerta', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('fecha_alerta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_alerta')
    )
    op.create_table('inventarios',
    sa.Column('id_inventario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('stock_maximo', sa.Integer(), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_inventario')
    )
    op.create_table('movimientos_inventario',
    sa.Column('id_movimiento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha_movimiento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_table('parametros_inventario',
    sa.Column('id_parametro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('costo_orden', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('costo_mantenimiento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lead_time_dias', sa.Integer(), nullable=True),
    sa.Column('stock_seguridad', sa.Integer(), nullable=True),
    sa.Column('punto_reorden', sa.Integer(), nullable=True),
    sa.Column('eoq', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_parametro')
    )
    op.create_table('predicciones',
    sa.Column('id_prediccion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_modelo', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('fecha_prediccion', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('periodo', sa.String(length=20), nullable=True),
    sa.Column('demanda_estimada', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_modelo'], ['modelos_ia.id_modelo'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_prediccion')
    )
    op.create_table('ventas',
    sa.Column('id_venta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_venta', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('detalle_ventas',
    sa.Column('id_detalle', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('reabastecimiento',
    sa.Column('id_reabastecimiento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_prediccion', sa.Integer(), nullable=True),
    sa.Column('fecha_generacion', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('cantidad_sugerida', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id_prediccion'], ['predicciones.id_prediccion'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_reabastecimiento')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.drop_index('ix_users_id')
        batch_op.drop_index('ix_users_username')

    op.drop_table('users')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_code')
        batch_op.drop_index('ix_products_id')

    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('min_stock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('reorder_point', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('max_stock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cost_price', mysql.FLOAT(), nullable=True),
    sa.Column('sell_price', mysql.FLOAT(), nullable=True),
    sa.Column('is_active', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_id', ['id'], unique=False)
        batch_op.create_index('ix_products_code', ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_username', ['username'], unique=True)
        batch_op.create_index('ix_users_id', ['id'], unique=False)
        batch_op.create_index('ix_users_email', ['email'], unique=True)

    op.drop_table('reabastecimiento')
    op.drop_table('detalle_ventas')
    op.drop_table('ventas')
    op.drop_table('predicciones')
    op.drop_table('parametros_inventario')
    op.drop_table('movimientos_inventario')
    op.drop_table('inventarios')
    op.drop_table('alertas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_correo'))

    op.drop_table('usuarios')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_codigo'))

    op.drop_table('productos')
    op.drop_table('modelos_ia')
    op.drop_table('roles')
    op.drop_table('proveedores')
    op.drop_table('dataset_entrenamiento')
    op.drop_table('categorias')
    # ### end Alembic commands ###
